# Generated by Django 3.1.7 on 2021-02-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_message', '0002_auto_20210202_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='cycle',
            field=models.CharField(choices=[('monthly', 'monthly'), ('quarter', 'quarter')], max_length=10, null=True),
        ),
    ]
