# Generated by Django 3.1.5 on 2021-02-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_message', '0003_portfoliocompany_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
