# Generated by Django 3.1.5 on 2021-03-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_message', '0007_auto_20210311_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocompany',
            name='commit_record',
            field=models.CharField(blank=True, default=' ', max_length=10000, null=True),
        ),
    ]
