# Generated by Django 3.1.5 on 2021-06-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_message', '0008_auto_20210311_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
